import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Box, AppBar, Toolbar, Typography, Button } from '@mui/material';

export default function Home() {

 const goSomewhereCool = () => {
  window.open("https://balajis.com/the-purpose-of-technology/", "_blank");
  }

  return (
    <Box sx={{ 
      display: 'flex', 
      flexDirection: 'column', 
      alignItems: 'center', 
      justifyContent: 'center', 
      height: '100vh' 
    }}>
      <Head>
        <title>Let's Go Biotech - Home Base</title>
        <meta name="description" content="Generated by Rohan Cain Robinson" />
      </Head>

      <AppBar position="fixed" color="secondary">
      <Toolbar>
        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
          LGB 🧬
        </Typography>
        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
        <span className={styles.cursorPointer} onClick={goSomewhereCool}>DO NOT CLICK HERE</span>  
        </Typography>

      </Toolbar>
    </AppBar>

      <Typography variant="h1" sx={{ mb: 4 }}>
        🧬 <b>Let's Go Biotech</b> 🚀
      </Typography>
      <Typography variant="h4" sx={{ fontStyle: 'italic', mb: 2 }}>
        Interested in badass sci-fi shit like CRISPR, neural interfaces, and STEM cells?
      </Typography>
      <Typography variant="h4" sx={{ mb: 6 }}>
        Learn biotech through engaging papers and quizzes!
      </Typography>
      <Box sx={{ 
        display: 'flex', 
        flexDirection: 'column', 
        alignItems: 'center', 
        justifyContent: 'center', 
        gap: 3 
      }}>
        {/* <Typography variant="body1" sx={{ mb: 1 }}>
          (1) Select an Exciting Paper
        </Typography>
        <Typography variant="body1" sx={{ mb: 1 }}>
          (2) Read its Abstract
        </Typography>
        <Typography variant="body1" sx={{ mb: 3 }}>
          (3) Take a Short Quiz.
        </Typography> */}
        <Button 
          variant="contained" 
          color="secondary" 
          size="large" 
          href="/select-paper"
          sx={{ fontWeight: 'bold' }}
        >
          Get Started
        </Button>
        <Typography variant="body1" sx={{ mb: 3 }}>
            (no need to provide email or create an account) <br/>
        </Typography>



      </Box>
    </Box>
  );
}

