import Head from 'next/head';

export default function Home() {
 return (
   <div>
     <Head>
       <title>Let's Go Biotech - Home Base</title>
       <meta name="description" content="Generated by create next app" />
       {/* <link rel="icon" href="/favicon.ico" /> */}
     </Head>
       <h1>
       🧬 Let's Go Biotech 🚀
       </h1>
      <br />
         <p><i>Biotechnology is taking off. We'll keep you updated.</i></p>{' '}
       <div>
         <a>
           <p> (1) Select a Paper you Find Exciting!</p>
         </a>
<br />
         <a>
           <p> (2) Read It!</p>
         </a>
<br />
         <a>
           <p>(3) Take a Short Quiz and Improve your Learning!</p>
         </a>
<br />
         <a href="/paper-curation">
           <h2>Let's Get Started</h2>
         </a>
       </div>
   </div>
 )
}
