import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import Link from 'next/link';
import { Box, AppBar, Toolbar, Typography, Button, Card, CardContent } from '@mui/material';



export default function ReadPaper() {

 const router = useRouter();
 const showPaper1 = router.query.showPaper1;
 const showPaper2 = router.query.showPaper2;
 const showPaper3 = router.query.showPaper3;

 //Paper 2
 const paperAbstract2 = "Inefficient knock-in of transgene cargos limits the potential of cell-based medicines. In this study, we used a CRISPR nuclease that targets a site within an exon of an essential gene and designed a cargo template so that correct knock-in would retain essential gene function while also integrating the transgene(s) of interest. Cells with non-productive insertions and deletions would undergo negative selection. This technology, called SLEEK (SeLection by Essential-gene Exon Knock-in), achieved knock-in efficiencies of more than 90% in clinically relevant cell types without impacting long-term viability or expansion";
 
 // Paper 1
 const paperAbstract1 = "The first gene therapies for tackling heart failure are making progress in the clinic. Rocket Pharmaceuticals aims shortly to start a pivotal phase 2 study of a gene therapy for patients with Danon disease, an X-linked dominant disorder that causes progressive heart failure and death in early adulthood. If successful, the trial will encourage a slew of developers of genetic medicines to believe that arresting or even reversing progressive heart failure is feasible in different disease settings.";
 
 // Paper 3
 const paperAbstract3 = "There have been numerous investigations targeted at identifying whether a drug lag exists in the mature markets of the US, EU and Japan. This work focuses on the emerging markets because of the potential they hold for the future of the pharmaceutical industry as a consequence of rapid economic and political development. The aims of this work are to ascertain whether a drug lag exists in the emerging markets and how it has changed over time from the 1960s to the 2000s. It will also highlight key regulatory barriers which may contribute to drug lag.The date of the marketing authorisation (MA) approval by the US Food and Drug Administration (FDA) was used as a reference point. A comparison against the company database regarding emerging market specific approval enabled the difference in time and thus the drug lag for that particular market to be calculated. This work concludes that the overall relative drug lag in the emerging markets has decreased over time and that there are seven key regulatory barriers which need to be targeted in order to make further improvements; ‘Western Approval’, local clinical development (LCD), Certificate of Pharmaceutical Product (CPP), Good Manufacturing Practice (GMP), pricing approval, document authentication and harmonisation.";


 return (
   <div className={styles.container}>
     <Head>
       <title>Let's Go Biotech - Read Paper</title>
       <meta name="description" content="Generated by Rohan in SF" />
       {/* <link rel="icon" href="/favicon.ico" /> */}
     </Head>

     <AppBar position="fixed" color="secondary">
      <Toolbar>
        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
          LGB 🧬
        </Typography>
      </Toolbar>
    </AppBar>

    <Typography variant="body1" sx={{ mb: 2, fontSize: "2.0rem" }}>
      <span className={styles.lgbDescription}>Read the Abstract for the Paper you chose and Take a Quiz when you're Ready!</span>
    </Typography>
    

     {showPaper1 === 'false' && showPaper2 === "false" && showPaper3 === "false" && (
        <div>
           <Typography variant="body1" sx={{ mb: 2, fontSize: "3.0rem" }}>
              <span className={styles.lgbDescription}>You did not select any papers to read, go back and select one!</span>
           </Typography>
        </div>
     )}
      <div>

        {/* { === 'true' && (
          <div className={styles.abstractDisplay}>
            <p><span className={styles.lgbDescription}>Abstract</span></p> 
            <p className={styles.abstractText}><b>{paperAbstract1}</b></p>
            <hr></hr>
          </div>
        )} */}

        {showPaper1 === 'true' && (
          <Card className={styles.abstractDisplay}>
            <CardContent>
              <Typography variant="h5" component="div">Abstract</Typography>
              <Typography variant="body2" color="text.secondary">
                {paperAbstract1}
              </Typography>
            </CardContent>
          </Card>
        )}

        {showPaper2 === 'true' && (
          <div className={styles.abstractDisplay}>
            <p><span className={styles.lgbDescription}>Abstract</span></p>
            <p className={styles.abstractText}><b>{paperAbstract2}</b></p>
            <hr></hr>
          </div>
        )}

        {showPaper3 === 'true' && (
          <div className={styles.abstractDisplay}>
            <p><span className={styles.lgbDescription}>Abstract</span></p> 
            <p className={styles.abstractText}><b>{paperAbstract3}</b></p>
            <hr></hr>
          </div>
        )}

    </div>

    <br />


      {/* <Link 
          className={styles.greenSquare}
          href={{
          pathname: '/take-quiz',
          query: {
            showPaper1: showPaper1,
            showPaper2: showPaper2,
            showPaper3: showPaper3
          }
        }}>
      <Typography variant="body1" sx={{ mb: 1.5 }}>
          <b>Take Quiz</b>
      </Typography>
        </Link> */}

        <Link
            className={styles.greenSquare} 
            href={{
                pathname: '/take-quiz',
                query: {
                  showPaper1: showPaper1,
                  showPaper2: showPaper2,
                  showPaper3: showPaper3
                }
            }}>
            <h2>Take Quiz</h2>
        </Link>

   

        <a href="/select-paper">
        <Typography variant="body1" sx={{ mb: 0.5 }}>
          &larr; <b>Select Papers</b>
      </Typography>
        </a>

   </div>
 )
}



