import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Link from 'next/link';



export default function SelectPaper() {

  const [showModal, setShowModal] = useState(false);
  const [showPaper1, setShowPaper1] = useState(false);
  const [showPaper2, setShowPaper2] = useState(false);
  const [showPaper3, setShowPaper3] = useState(false);
  
 return (
   <div className={styles.container}>
     <Head>
       <title>Let's Go Biotech - Select Paper</title>
       <meta name="description" content="Generated by create next app" />
       {/* <link rel="icon" href="/favicon.ico" /> */}
     </Head>
       <h1>
       🧬 Let's Go Biotech 🚀
       </h1>
      <br />
      <div className={styles.paperSelection}>
          <p>Howdy there 🤠 <br /> Each of these papers covers an innovative area happening rn in health and biotechnology.</p>
          <br />
          <div className={styles.choosePaper}>
                <div className={styles.item} onClick={() => [setShowModal(true), setShowPaper1(true)]}><b>Foundation Generalist Medical AI Model</b> &nbsp;</div> <br /> 
                {showModal && showPaper1 && (
            <div className={styles.modal}>
              <p>Learn about flexible, highly capable AI models that interpret diverse data modalities - introducing Generalist Medical AI.</p>
              <button onClick={() => [setShowModal(false), setShowPaper1(false)]}>Close Description</button>
            </div>
                )}

                <div className={styles.item} onClick={() => [setShowModal(true), setShowPaper2(true)]}><b>FHIR Genomics</b> &nbsp;</div> <br /> 
                {showModal && showPaper2 && (
            <div className={styles.modal}>
              <p>Learn about how the FHIR standard simplifies complex clinical genomic data exchange with next-gen sequencing, enabling precision medicine.</p>
              <button onClick={() => [setShowModal(false), setShowPaper2(false)]}>Close Description</button>
            </div>
                )}
               
                <div className={styles.item} onClick={() => [setShowModal(true), setShowPaper3(true)]}><b>Yamanaka Factors</b> &nbsp;</div>
                {showModal && showPaper3 && (
                        <div className={styles.modal}>
                          <p>Learn about the method to turn adult cells into embryonic-like stem cells with only four factors, revolutionizing potential for regenerative medicine.</p>
                          <button onClick={() => [setShowModal(false), setShowPaper3(false)]}>Close Description</button>
                        </div>
                )}
          </div>
      </div>

      <br />
      <br />

 
        <Link 
          className={styles.greenSquare}
          href={{
          pathname: '/read-paper',
          query: {
            showPaper1: showPaper1,
            showPaper2: showPaper2,
            showPaper3: showPaper3
          }
        }}>
          <h2>Read Selected Papers</h2>
          {showPaper1 ? (<p>Foundation GMAI</p>): ""}
          {showPaper2 ? (<p>FHIR Genomics</p>): ""}
          {showPaper3 ? (<p>Yamanaka Factors</p>): ""}
        </Link>
  


        <a href="/">
          <h2>Back to Home Page</h2>
        </a>
   </div>
 )
}
