import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Link from 'next/link';
import { Box, AppBar, Toolbar, Typography, Button } from '@mui/material';


export default function TakeQuiz() {

  // -these values come from read-paper.js 
  const router = useRouter();
  const showPaper1 = router.query.showPaper1;
  const showPaper2 = router.query.showPaper2;
  const showPaper3 = router.query.showPaper3;

  // --these values come from user input 
  const [showScore, setShowScore] = useState(false);
  const [totalQuestions, setTotalQuestions] = useState('');
  const [totalCorrect, setCorrect] = useState('');

  // --updated hooks for new quiz w/ multiple answers per question
  const [paper1Q1Value, setPaper1Q1Value] = useState('');
  const [paper1Q2Value, setPaper1Q2Value] = useState(' ');
  const [paper2Q1Value, setPaper2Q1Value] = useState('');
  const [paper2Q2Value, setPaper2Q2Value] = useState(' ');  
  const [paper3Q1Value, setPaper3Q1Value] = useState('');
  const [paper3Q2Value, setPaper3Q2Value] = useState(' ');

  const goHome = () => {
    window.location.href = "http://letsgobiotech.com"; 
  }



  // handle paper 1 change 
  const handlePaper1Change = (event) => {
    const { name, value } = event.target;
    if (name === 'paper1-q1') {
      setPaper1Q1Value(value);
    } 
    else if (name === 'paper1-q2') {
      setPaper1Q2Value(value);
    }
  }
  // handle paper 2 change
  const handlePaper2Change = (event) => {
    const { name, value } = event.target;
    if (name === 'paper2-q1') {
      setPaper2Q1Value(value);
    }
    else if (name === 'paper2-q2') {
      setPaper2Q2Value(value);
    }
  }
  // handle paper 3 change
  const handlePaper3Change = (event) => { 
    const { name, value } = event.target;
    if (name === 'paper3-q1') {
      setPaper3Q1Value(value);
    }
    else if (name === 'paper3-q2') {
      setPaper3Q2Value(value);
    }
  }

  const scoreFun = () => {
    
    // correct answers to v6 quiz in order from q1 to qn
    const correctAnswersPaper1 = ['paper1-q1-a', 'paper1-q2-c'];
    const correctAnswersPaper2 = ['paper2-q1-a', 'paper2-q2-c'];
    const correctAnswersPaper3 = ['paper3-q1-a', 'paper3-q2-c'];

    let totalCorrect = 0;
    let totalQuestions = correctAnswersPaper1.length; 
    
    if (showPaper1 === 'true') {
      const userAnswers = [paper1Q1Value, paper1Q2Value];
      console.log(userAnswers);
      console.log(correctAnswersPaper1);
      totalCorrect = scorePaper(correctAnswersPaper1, userAnswers);
      console.log(totalCorrect);
    }

    if (showPaper2 === 'true')  {
      const userAnswers = [paper2Q1Value, paper2Q2Value];
      console.log(userAnswers);
      console.log(correctAnswersPaper2);
      totalCorrect = scorePaper(correctAnswersPaper2, userAnswers);
      console.log(totalCorrect);
    }

    if (showPaper3 === 'true') {
      const userAnswers = [paper3Q1Value, paper3Q2Value];
      console.log(userAnswers);
      console.log(correctAnswersPaper3);
      totalCorrect = scorePaper(correctAnswersPaper3, userAnswers);
      console.log(totalCorrect);
    }

    setTotalQuestions(totalQuestions);
    setCorrect(totalCorrect);

  }

  function scorePaper(correctAnswers, userAnswers) {
    let numQuestionsCorrect = 0
    for (let i = 0; i < correctAnswers.length; i++) {
        
        const correctAnswer = correctAnswers[i];
        const userAnswer = userAnswers[i];
        console.log(correctAnswer, userAnswer);
        if (correctAnswer === userAnswer) {
          numQuestionsCorrect += 1;
        }

    } 
    return numQuestionsCorrect; 
  }


 return (
   <div className={styles.container}>
      <Head>
        <title>Let's Go Biotech - Quiz</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AppBar position="fixed" color="secondary">
        <Toolbar>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }} className={styles.cursorPointer} onClick={goHome}>
            Let's Go Biotech 
          </Typography>
        </Toolbar>
      </AppBar>

      <br />

      {showPaper1 === 'true' && (
      <div className={styles.quizHellYa}>
        <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
          <span className={styles.lgbText}><i><b>Which biological systems employ complementarity between a guide RNA and target nucleic acid sequences for recognition of genetic elements?</b></i></span><br />
          <input type="radio" id="paper1-q1-a" name="paper1-q1" value="paper1-q1-a" onChange={handlePaper1Change}/>
          <label htmlFor="paper1-a"><span className={styles.lgbText}>Prokaryotic CRISPR-Cas systems</span></label><br />
          <input type="radio" id="paper1-q1-b" name="paper1-q1" value="paper1-q1-b" onChange={handlePaper1Change} />
          <label htmlFor="paper1-b"><span className={styles.lgbText}>Eukaryotic RNA interference</span></label><br />
          <input type="radio" id="paper1-q1-c" name="paper1-q1" value="paper1-q1-c" onChange={handlePaper1Change} />
          <label htmlFor="paper1-q1-c"><span className={styles.lgbText}>Ribosomal RNA modification</span></label><br /> <br />
       
          <span className={styles.lgbText}><i><b>Which prokaryotic RNA-guided system was recently reported and has RNA-guided endonuclease activity?</b></i></span><br />
          <input type="radio" id="paper1-q2-a" name="paper1-q2" value="paper1-q2-a" onChange={handlePaper1Change}/>
          <label htmlFor="paper1-q2-a"><span className={styles.lgbText}>CRISPR-Cas9</span></label><br />
          <input type="radio" id="paper1-q2-b" name="paper1-q2" value="paper1-q2-b" onChange={handlePaper1Change} />
          <label htmlFor="paper1-q2-b"><span className={styles.lgbText}>CRISPR-Cas12</span></label><br />
          <input type="radio" id="paper1-q2-c" name="paper1-q2" value="paper1-q2-c" onChange={handlePaper1Change} />
          <label htmlFor="paper1-q2-c"><span className={styles.lgbText}>OMEGA effector TnpB</span></label>
        </Typography>
      </div>
      )}

      <br />

      {showPaper2 === 'true' && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}><i><b>What term do the authors use to describe the metric strongly correlated with RNA expression level?</b></i></span><br />
            <input type="radio" id="paper2-q1-a" name="paper2-q1" value="paper2-q1-a" onChange={handlePaper2Change} />
            <label htmlFor="paper2-a"><span className={styles.lgbText}>Promoter fragmentation entropy (PFE)</span></label><br />
            <input type="radio" id="paper2-q1-b" name="paper2-q1" value="paper2-q1-b" onChange={handlePaper2Change} />
            <label htmlFor="paper2-b"><span className={styles.lgbText}>Nucleosome depletion index (NDI)</span></label><br />
            <input type="radio" id="paper2-q1-c" name="paper2-q1" value="paper2-q1-c" onChange={handlePaper2Change} />
            <label htmlFor="paper2-c"><span className={styles.lgbText}>Transcription start site variability (TSSV)</span></label><br /> <br />

            <span className={styles.lgbText}><i><b>What is the main application of the introduced metric, PFE?</b></i></span><br />
            <input type="radio" id="paper2-q2-a" name="paper2-q2" value="paper2-q2-a" onChange={handlePaper2Change} />
            <label htmlFor="paper2-d"><span className={styles.lgbText}>Monitoring biological processes in the blood</span></label><br />
            <input type="radio" id="paper2-q2-b" name="paper2-q2" value="paper2-q2-b" onChange={handlePaper2Change} />
            <label htmlFor="paper2-e"><span className={styles.lgbText}> Predicting the size variability of cfDNA fragments</span></label><br />
            <input type="radio" id="paper2-q2-c" name="paper2-q2" value="paper2-q2-c" onChange={handlePaper2Change} />
            <label htmlFor="paper2-f"><span className={styles.lgbText}>Detecting and classifying cancer from cfDNA</span></label><br /> <br />
          </Typography>
        </div>
      )}

      <br />

      {showPaper3 === 'true' && (
        <div className={styles.quizHellYa}>
        <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
          <span className={styles.lgbText}><b>What does BioLORD establish a new state of the art for?</b></span><br />
          <input type="radio" id="paper3-q1-a" name="paper3-q1" value="paper3-q1-a" onChange={handlePaper3Change} />
          <label htmlFor="paper3-a"><span className={styles.lgbText}>Text similarity in clinical sentences</span></label><br />
          <input type="radio" id="paper3-q1-b" name="paper3-q1" value="paper3-q1-b" onChange={handlePaper3Change} />
          <label htmlFor="paper3-b"><span className={styles.lgbText}>Biomedical ontologies and hierarchies</span></label><br /> <br />
      
          <span className={styles.lgbText}><b>How does BioLORD overcome the issue of non-semantic representations?</b></span><br />
          <input type="radio" id="paper3-q2-a" name="paper3-q2" value="paper3-q2-a" onChange={handlePaper3Change} />
          <label htmlFor="paper3-c"><span className={styles.lgbText}>By maximizing the similarity in representation of names referring to the same concept</span></label><br />
          <input type="radio" id="paper3-q2-b" name="paper3-q2" value="paper3-q2-b" onChange={handlePaper3Change} />
          <label htmlFor="paper3-d"><span className={styles.lgbText}>By preventing collapse through contrastive learning</span></label><br />
          <input type="radio" id="paper3-q2-c" name="paper3-q2" value="paper3-q2-c" onChange={handlePaper3Change} />
          <label htmlFor="paper3-d"><span className={styles.lgbText}>By grounding concept representations using definitions and short descriptions from a biomedical knowledge graph</span></label><br />
        </Typography>
      </div>
      )} 

      <br />
      <br />


      {showScore && totalCorrect > 0 &&(
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}>Great job on reading new & hard material!< br />
            You got {totalCorrect} correct out of {totalQuestions}!</span> <br />

            <br />
            
            <Link className={styles.greenSquare} href="/" >
                <h2><span className={styles.lgbText}>Let's Try a New One!</span></h2>
            </Link>

          </Typography>
        </div>
      )}

      {showScore && totalCorrect === 0 && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
              <span className={styles.lgbText}>Great job on reading the paper and trying to understand something complicated! < br />
              You didn't get any of the questions correct, no worries! <br /> <br />
              Re-read the abstract &darr; and try again!<br />
              </span>
            <Link className={styles.greenSquare} href="/">
            <h2><span className={styles.lgbText}>Back to Paper Selection!</span></h2>
            </Link> <br />
          </Typography>
        </div>
      )}

      {!showScore && (
      <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
        
        <Link className={styles.greenSquare} href="#" onClick={() => [ scoreFun() , setShowScore(true)]}>
            <h2><span className={styles.lgbText}>Finished? Let's See How You Did!</span></h2>
        </Link>
    
      </Typography>
      )}

   </div>
 )
}
