import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Link from 'next/link';

export default function TakeQuiz() {

  // these values come from read-paper.js
  const router = useRouter();
  const showPaper1 = router.query.showPaper1;
  const showPaper2 = router.query.showPaper2;
  const showPaper3 = router.query.showPaper3;

  // variables based on user input 
  const [gmaiValue, setGmaiValue] = useState('');
  const [fhirValue, setFhirValue] = useState('');
  const [yfValue, setYfValue] = useState('');
  const [showScore, setShowScore] = useState(false);
  const [totalQuestions, setTotalQuestions] = useState('');
  const [totalCorrect, setCorrect] = useState('');



  // handleGmaiChange
  const handleGmaiChange = (event) => {
    setGmaiValue(event.target.value);
  }

  // handleFHIRChange
  const handleFHIRChange = (event) => {
    setFhirValue(event.target.value);
  }

  // handleYamanakaChange
  const handleYamanakaChange = (event) => { 
    setYfValue(event.target.value);
  }

  const scoreFun = () => {

    let totalCorrect = 0;
    let totalQuestions = 0;
    
    // correct answers to v2 quiz
    const correctAnswerPaper1 = 'GMAI-2';
    const correctAnswerPaper2 = 'FHIR-1';
    const correctAnswerPaper3 = 'YF-2';
      console.log("input-", gmaiValue, fhirValue, yfValue);
    // get all the choices the user selected
    if (showPaper1 === 'true') {
   //  console.log( "q1-", gmaiValue === correctAnswerPaper1);
     totalQuestions += 1;

     if (gmaiValue === correctAnswerPaper1) {
      totalCorrect += 1;
     }
    }

    if (showPaper2 === 'true')  {
    //  console.log("q2-", fhirValue, correctAnswerPaper2);
      totalQuestions += 1;

      if (fhirValue === correctAnswerPaper2) {
        totalCorrect += 1;
      }
    }

    if (showPaper3 === 'true') {
     // console.log("q3-", yfValue, correctAnswerPaper3);
      totalQuestions += 1;

      if (yfValue === correctAnswerPaper3) {
        totalCorrect += 1;
      }
    }

    console.log("total correct-", totalCorrect, "total questions-", totalQuestions);
    setTotalQuestions(totalQuestions);
    setCorrect(totalCorrect);

  }


 return (
   <div className={styles.container}>
     <Head>
       <title>Let's Go Biotech - Quiz</title>
       <meta name="description" content="Generated by create next app" />
       {/* <link rel="icon" href="/favicon.ico" /> */}
     </Head>
       <h1>
       🧬 Let's Go Biotech - Quiz 🚀
       </h1>
      <br />

      {showPaper1 === 'false' && showPaper2 === "false" && showPaper3 === "false" && (
        <div className={styles.quizHellYa}>
          <p>You did not select any papers to read, go back and select some!</p>
        </div>
     )}

      {showPaper1 === 'true' && (
        <div className={styles.quizHellYa}>
          <span><i><b>What's the biggest shift in thinking that GMAI will have vs. the status quo?</b></i></span><br />
          <input type="checkbox" id="GMAI-1" name="GMAI-1" value="GMAI-1" onChange={handleGmaiChange}/>
          <label htmlFor="GMAI-1">The models are smarter than medical practitioners</label><br />
          <input type="checkbox" id="GMAI-2" name="GMAI-2" value="GMAI-2" onChange={handleGmaiChange} />
          <label htmlFor="GMAI-2">The models can solve medical problems that they haven't been directly trained for</label><br />
          <input type="checkbox" id="GMAI-3" name="GMAI-3" value="GMAI-3" onChange={handleGmaiChange} />
          <label htmlFor="GMAI-3">The models can operate well with crappy training data</label><br />
        </div>
      )}

      <br />

      {showPaper2 === 'true' && (
        <div className={styles.quizHellYa}>
          <span><i><b>What is the largest benefit of the FHIR standard to Genomics?</b></i></span><br />
          <input type="checkbox" id="FHIR-1" name="FHIR-1" value="FHIR-1" onChange={handleFHIRChange} />
          <label htmlFor="FHIR-1">Exchanging complex clinical genomic data</label><br />
          <input type="checkbox" id="FHIR-2" name="FHIR-2" value="FHIR-2" onChange={handleFHIRChange} />
          <label htmlFor="FHIR-2">Making DNA sequencing machines faster</label><br />
          <input type="checkbox" id="FHIR-3" name="FHIR-3" value="FHIR-3" onChange={handleFHIRChange} />
          <label htmlFor="FHIR-3">Faciliating international collobartion on pandemics</label><br />
        </div>
      )}

      <br />

      {showPaper3 === 'true' && (
        <div className={styles.quizHellYa}>
          <span><b>Which of the following below is NOT a factor identified in the Yamanaka paper?</b></span><br />
          <input type="checkbox" id="YF-1" name="YF-1" value="YF-1" onChange={handleYamanakaChange} />
          <label htmlFor="YF-1">Oct3/4</label><br />
          <input type="checkbox" id="YF-2" name="YF-2" value="YF-2" onChange={handleYamanakaChange} />
          <label htmlFor="YF-2">MYB</label><br />
          <input type="checkbox" id="YF-3" name="YF-3" value="YF-3" onChange={handleYamanakaChange}/>
          <label htmlFor="YF-3">Klf4</label><br />
        </div>
      )} 

      <br />
      <br />


      {showScore && totalCorrect > 0 &&(
        <div className={styles.quizHellYa}>
            Nice, good job on reading new, hard material and taking a quiz! < br />
            You got {totalCorrect} correct out of {totalQuestions}!
        </div>
      )}

      {showScore && totalCorrect === 0 && (
        <div className={styles.quizHellYa}>
            Nice, good job on reading the paper and trying to understand something complicated! < br />
            You didn't get any of the questions correct, no worries! <br /> <br />
            Read the abstracts again and retry! <br />
          <Link className={styles.greenSquare} href="/select-paper">
          <h2>Back to Paper Selection!</h2>
          </Link>

        </div>
      )}

      {!showScore && (
      <Link className={styles.greenSquare} href="#" onClick={() => [ scoreFun() , setShowScore(true)]}>
          <h2>Finished? Let's See How You Did!</h2>
      </Link>)
      }


 


       <a href="/read-paper">
           <h2>Back to Read Papers Page</h2>
         </a>

   </div>
 )
}
