import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Link from 'next/link';
import { Box, AppBar, Toolbar, Typography, Button } from '@mui/material';


export default function TakeQuiz() {

  // these values come from read-paper.js
  const router = useRouter();
  const showPaper1 = router.query.showPaper1;
  const showPaper2 = router.query.showPaper2;
  const showPaper3 = router.query.showPaper3;

  // variables based on user input 
  const [paper1Value, setPaper1Value] = useState('');
  const [paper2Value, setPaper2Value] = useState('');
  const [paper3Value, setPaper3Value] = useState('');
  const [showScore, setShowScore] = useState(false);
  const [totalQuestions, setTotalQuestions] = useState('');
  const [totalCorrect, setCorrect] = useState('');



  // handle paper 1 change 
  const handlePaper1Change = (event) => {
    setPaper1Value(event.target.value);
  }

  // handle paper 2 change
  const handlePaper2Change = (event) => {
    setPaper2Value(event.target.value);
  }

  // handle paper 3 change
  const handlePaper3Change = (event) => { 
    setPaper3Value(event.target.value);
  }

  const scoreFun = () => {

    let totalCorrect = 0;
    let totalQuestions = 0;
    
    // correct answers to v2 quiz
    const correctAnswerPaper1 = 'paper1-c';
    const correctAnswerPaper2 = 'paper2-a';
    const correctAnswerPaper3 = 'paper3-c';
    console.log("input-", paper1Value, paper2Value, paper3Value);
    // get all the choices the user selected
    if (showPaper1 === 'true') {
   //  console.log( "q1-", gmaiValue === correctAnswerPaper1);
     totalQuestions += 1;

     if (paper1Value === correctAnswerPaper1) {
      totalCorrect += 1;
     }
    }

    if (showPaper2 === 'true')  {
    //  console.log("q2-", fhirValue, correctAnswerPaper2);
      totalQuestions += 1;

      if (paper2Value === correctAnswerPaper2) {
        totalCorrect += 1;
      }
    }

    if (showPaper3 === 'true') {
     // console.log("q3-", yfValue, correctAnswerPaper3);
      totalQuestions += 1;

      if (paper3Value === correctAnswerPaper3) {
        totalCorrect += 1;
      }
    }

    console.log("total correct-", totalCorrect, "total questions-", totalQuestions);
    setTotalQuestions(totalQuestions);
    setCorrect(totalCorrect);

  }


 return (
   <div className={styles.container}>
      <Head>
        <title>Let's Go Biotech - Quiz</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <AppBar position="fixed" color="secondary">
        <Toolbar>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            LGB 🧬
          </Typography>
        </Toolbar>
      </AppBar>

      <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
       <span className={styles.lgbDescription}>Instructions &rarr; Check an answer BEFORE clicking on the green button </span>
      </Typography>

      {showPaper1 === 'true' && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}><i><b>What is the name of the X-linked dominant disorder that causes progressive heart failure and death in early adulthood, and which Rocket Pharmaceuticals aims to target with its gene therapy?</b></i></span><br />
            <input type="radio" id="paper1-a" name="paper1" value="paper1-q1-a" onChange={handlePaper1Change}/>
            <label htmlFor="paper1-a">Down syndrome</label><br />
            <input type="radio" id="paper1-b" name="paper1" value="paper1-q1-b" onChange={handlePaper1Change} />
            <label htmlFor="paper1-b">Danon disease</label><br />
            <input type="radio" id="paper1-c" name="paper1" value="paper1-q1-c" onChange={handlePaper1Change} />
            <label htmlFor="paper1-c">Huntington's disease</label><br /> <br />

            <span className={styles.lgbText}><i><b>If the phase 2 study of Rocket Pharmaceuticals' gene therapy for Danon disease is successful, what impact could it have on developers of genetic medicines targeting heart failure?</b></i></span><br />
            <input type="radio" id="paper1-a" name="paper1" value="paper1-q2-a" onChange={handlePaper1Change}/>
            <label htmlFor="paper1-a">No Impact</label><br />
            <input type="radio" id="paper1-b" name="paper1" value="paper1-q2-b" onChange={handlePaper1Change} />
            <label htmlFor="paper1-b">Encouraging more research into heart failure therapies</label><br />
            <input type="radio" id="paper1-c" name="paper1" value="paper1-q2-c" onChange={handlePaper1Change} />
            <label htmlFor="paper1-c">Halting research into heart failure therapies</label>
          </Typography>
        </div>
      )}

      <br />

      {showPaper2 === 'true' && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}><i><b>What is the technology called that achieved knock-in efficiencies of more than 90% in clinically relevant cell types?</b></i></span><br />
            <input type="radio" id="paper2-a" name="paper2" value="paper2-a" onChange={handlePaper2Change} />
            <label htmlFor="paper2-a">SLEEK</label><br />
            <input type="radio" id="paper2-b" name="paper2" value="paper2-b" onChange={handlePaper2Change} />
            <label htmlFor="paper2-b">CRISPR nuclease</label><br />
            <input type="radio" id="paper2-c" name="paper2" value="paper2-c" onChange={handlePaper2Change} />
            <label htmlFor="paper2-c">Essential-gene Exon Knock-in</label><br /> <br />

            <span className={styles.lgbText}><i><b>How did the cargo template designed for knock-in retain essential gene function while integrating the transgene(s) of interest?</b></i></span><br />
            <input type="radio" id="paper2-a" name="paper2" value="paper2-a" onChange={handlePaper2Change} />
            <label htmlFor="paper2-a">By targeting a site within an intron of an essential gene</label><br />
            <input type="radio" id="paper2-b" name="paper2" value="paper2-b" onChange={handlePaper2Change} />
            <label htmlFor="paper2-b">By targeting a site within an exon of an essential gene</label><br />
            <input type="radio" id="paper2-c" name="paper2" value="paper2-c" onChange={handlePaper2Change} />
            <label htmlFor="paper2-c">by targeting a site within a promoter region of an essential gene</label><br /> <br />
          </Typography>
        </div>
      )}

      <br />

      {showPaper3 === 'true' && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}><b>What is the focus of this study on drug lag, and why are emerging markets relevant?</b></span><br />
            <input type="radio" id="" name="paper3" value="paper3-a" onChange={handlePaper3Change} />
            <label htmlFor="paper3-a">Focus: Investigate drug lag in emerging markets</label><br />
            <input type="radio" id="paper3-b" name="paper3" value="paper3-b" onChange={handlePaper3Change} />
            <label htmlFor="paper3-b">Relevance: Emerging markets have potential for the future of pharmaceutical industry due to rapid economic and political development.</label><br /> <br />
            
            <span className={styles.lgbText}><b>How was drug lag calculated in this study?</b></span><br />
            <input type="radio" id="  " name="paper3" value="paper3-a" onChange={handlePaper3Change} />
            <label htmlFor="paper3-a">Using date of marketing authorization (MA) approval by the US FDA as reference point, and comparing against company database of emerging market approvals.</label><br />
            <input type="radio" id="paper3-b" name="paper3" value="paper3-b" onChange={handlePaper3Change} />
            <label htmlFor="paper3-b">Using date of MA approval by the EMA as reference point and comparing against emerging market database.</label><br />
            <input type="radio" id="" name="paper3" value="paper3-c" onChange={handlePaper3Change} /> 
            <label htmlFor="paper3-c">Using date of MA approval by the WHO as reference point and comparing against global database.</label> <br /> <br />
          </Typography>
        </div>
      )} 

      <br />
      <br />


      {showScore && totalCorrect > 0 &&(
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
            <span className={styles.lgbText}>Great job on reading new & hard material completing the quiz! < br />
            You got {totalCorrect} correct out of {totalQuestions}!</span> <br />

            <br />
            
            <Link className={styles.greenSquare} href="/select-paper" >
                <h2>Let's Try a New One!</h2>
            </Link>

          </Typography>
        </div>
      )}

      {showScore && totalCorrect === 0 && (
        <div className={styles.quizHellYa}>
          <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
              Great job on reading the paper and trying to understand something complicated! < br />
              You didn't get any of the questions correct, no worries! <br /> <br />
              Re-read the abstract &darr; and try again!<br />
            <Link className={styles.greenSquare} href="/select-paper">
            <h2>Back to Paper Selection!</h2>
            </Link> <br />
          </Typography>
        </div>
      )}

      {!showScore && (
      <Typography variant="body1" sx={{ mb: 2, fontSize: "1.5rem" }}>
        <Link className={styles.greenSquare} href="#" onClick={() => [ scoreFun() , setShowScore(true)]}>
            <h2>Finished? Let's See How You Did!</h2>
        </Link>
      </Typography>
      )}

   </div>
 )
}
